pipeline {
    agent {
        docker { image 'node:14-alpine' } 
    }
    stages {
        stage('Docker node version') {
            steps {
                sh 'node --version'
            }
        }
    }
}
